import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";

const font = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="lg:px-[60px] px-5 " lang="en">
      <body className={font.className}>
        <Topbar />
        {children}
      </body>
    </html>
  );
}
